services:
    admin.category:
        class: AppBundle\SonataAdmin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            -
             name: sonata.admin
             manager_type: orm
             label: Category
             group: sidebar.builder

    admin.product:
        class: AppBundle\SonataAdmin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
            -
              name: sonata.admin
              group: sidebar.builder
              manager_type: orm
              label: Product